theme: jekyll-theme-minimal
title: 邓磊的Github主页
description: >
   欢迎来到我的个人博客，这是一个由Github Pages搭建的知识分享平台！
   在这里，您可以找到丰富的原创内容，涵盖技术笔记、编程教程、项目分享以及个人见解。
   我致力于通过深入浅出的文章和实用的代码示例，帮助大家在学习和实践中不断成长。
permalink: /posts/:title
plugins:
  - jekyll-feed
  - jekyll-seo-tag
